// Multi-point Buoyancy & Hydrodynamics Physics Engine
import * as THREE from 'three';
import { SHIP_CONFIG, GRAVITY } from './constants.js';
import { sampleOcean } from './gerstner.js';

export class ShipPhysics {
  constructor(shipObject) {
    this.ship = shipObject;

    // Physical state
    this.position = new THREE.Vector3(0, 0, 0);
    this.linearVelocity = new THREE.Vector3(0, 0, 0);
    
    this.quaternion = new THREE.Quaternion();
    this.angularVelocity = new THREE.Vector3(0, 0, 0); // pitch, yaw, roll rates

    // Control state
    this.throttle = 0;       // -1.0 to 1.0
    this.rudder = 0;         // -1.0 to 1.0
    this.targetThrottle = 0;
    this.targetRudder = 0;

    // Output telemetry
    this.speedKnots = 0;
    this.headingDeg = 0;
    this.currentWaveHeight = 0;
    this.rollDeg = 0;
    this.pitchDeg = 0;

    // Bow Thruster (-1.0 Port, +1.0 Starboard)
    this.bowThruster = 0;
    this.targetBowThruster = 0;

    // Navigation & Waypoint Autopilot
    this.autopilot = false;
    this.waypoints = [
      { name: 'Channel Marker 1', x: 0, z: 160 },
      { name: 'Cape Horizon Approach', x: 280, z: 420 },
      { name: 'Lighthouse Anchorage', x: 440, z: 580 },
      { name: 'The Needles Passage', x: -380, z: 320 },
      { name: 'Open Ocean Patrol', x: 0, z: 0 }
    ];
    this.activeWaypointIndex = 0;
    this.distToWaypoint = 0;
    this.bearingToWaypoint = 0;
    this.currentDepthMeters = 58.0;
    this.shallowAlarm = false;
  }

  setControls(throttleInput, rudderInput) {
    this.targetThrottle = THREE.MathUtils.clamp(throttleInput, -0.6, 1.0);
    this.targetRudder = THREE.MathUtils.clamp(rudderInput, -1.0, 1.0);
  }

  setBowThruster(val) {
    this.targetBowThruster = THREE.MathUtils.clamp(val, -1.0, 1.0);
  }

  setAutopilot(active) {
    this.autopilot = active;
  }

  update(dt, time, waveScale = 1.0, archipelago = null) {
    // 0. Waypoint Autopilot Navigation
    if (this.autopilot) {
      const wp = this.waypoints[this.activeWaypointIndex];
      const toWp = new THREE.Vector3(wp.x - this.position.x, 0, wp.z - this.position.z);
      this.distToWaypoint = toWp.length();
      const targetHeading = Math.atan2(toWp.x, toWp.z);
      this.bearingToWaypoint = Math.round(((targetHeading * 180) / Math.PI + 360) % 360);

      const currentHeadingRad = (this.headingDeg * Math.PI) / 180;
      let headingError = targetHeading - currentHeadingRad;
      while (headingError > Math.PI) headingError -= Math.PI * 2;
      while (headingError < -Math.PI) headingError += Math.PI * 2;

      this.targetRudder = THREE.MathUtils.clamp(-headingError * 2.2, -1.0, 1.0);
      this.targetThrottle = 0.85;

      if (this.distToWaypoint < 42.0) {
        this.activeWaypointIndex = (this.activeWaypointIndex + 1) % this.waypoints.length;
      }
    }

    // 1. Smooth control inputs (engine throttle lag, hydraulic rudder, electric bow thruster)
    this.throttle = THREE.MathUtils.damp(this.throttle, this.targetThrottle, 2.2, dt);
    this.rudder = THREE.MathUtils.damp(this.rudder, this.targetRudder, 4.5, dt);
    this.bowThruster = THREE.MathUtils.damp(this.bowThruster, this.targetBowThruster, 6.0, dt);

    // Ship local orientation vectors
    const forward = new THREE.Vector3(0, 0, 1).applyQuaternion(this.quaternion).normalize();
    const up = new THREE.Vector3(0, 1, 0).applyQuaternion(this.quaternion).normalize();
    const right = new THREE.Vector3(1, 0, 0).applyQuaternion(this.quaternion).normalize();

    // 2. Accumulate Forces & Torques
    const totalForce = new THREE.Vector3(0, -SHIP_CONFIG.mass * GRAVITY, 0); // Gravity
    const totalTorque = new THREE.Vector3(0, 0, 0);

    // Multi-point probe buoyancy calculation
    let submergedCount = 0;
    let avgWaterHeight = 0;

    for (const probe of SHIP_CONFIG.probes) {
      // World position of the probe on the hull
      const localProbe = new THREE.Vector3(probe.x, probe.y, probe.z);
      const worldProbe = localProbe.clone().applyQuaternion(this.quaternion).add(this.position);

      // Probe velocity
      const r = localProbe.clone().applyQuaternion(this.quaternion);
      const probeVel = this.linearVelocity.clone().add(this.angularVelocity.clone().cross(r));

      // Query wave height & normal at probe position
      const oceanSample = sampleOcean(worldProbe.x, worldProbe.z, time, waveScale);
      const submersion = oceanSample.height - worldProbe.y;
      avgWaterHeight += oceanSample.height;

      if (submersion > 0) {
        submergedCount++;
        // Spring + Damping buoyancy force
        const fUp = (SHIP_CONFIG.buoyancyStiffness * submersion - SHIP_CONFIG.buoyancyDamping * probeVel.y) * probe.weight;
        const clampedFUp = Math.max(0, fUp);

        const forceVec = new THREE.Vector3(0, clampedFUp, 0);
        totalForce.add(forceVec);

        // Torque generated by this hull probe: tau = r x F
        const torque = r.clone().cross(forceVec);
        totalTorque.add(torque);
      }
    }

    avgWaterHeight /= SHIP_CONFIG.probes.length;
    this.currentWaveHeight = Math.abs(avgWaterHeight);

    // 3. Propulsion & Rudder Steering
    const thrustMagnitude = this.throttle >= 0
      ? this.throttle * SHIP_CONFIG.maxEnginePower
      : this.throttle * SHIP_CONFIG.maxReversePower;

    const thrustForce = forward.clone().multiplyScalar(thrustMagnitude);
    totalForce.add(thrustForce);

    // Rudder creates turning torque only when ship is moving through water
    const forwardSpeed = this.linearVelocity.dot(forward);
    this.speedKnots = forwardSpeed * 1.94384; // m/s to knots

    const rudderTorqueMagnitude = -this.rudder * SHIP_CONFIG.maxRudderAngle * forwardSpeed * 4500.0;
    totalTorque.y += rudderTorqueMagnitude;

    // Centrifugal rolling moment (ship heels outward during turns)
    const heelTorque = this.rudder * forwardSpeed * 5200.0;
    totalTorque.z += heelTorque;

    // 3b. Electric Bow Thruster Force & Turning Moment (360° spin & crab docking)
    if (Math.abs(this.bowThruster) > 0.01) {
      const thrusterMag = this.bowThruster * 34000.0;
      totalForce.add(right.clone().multiplyScalar(thrusterMag));
      // Moment arm at bow (7.2m forward of center of gravity)
      totalTorque.y -= thrusterMag * 7.2;
    }

    // 4. Hydrodynamic Resistance (Linear & Angular Drag)
    // Lateral drag (ships resist sideways sliding heavily)
    const lateralSpeed = this.linearVelocity.dot(right);
    const lateralDragForce = right.clone().multiplyScalar(-lateralSpeed * SHIP_CONFIG.dragLinear * 4.5);
    totalForce.add(lateralDragForce);

    // Forward drag (increases with square of speed)
    const forwardDragForce = forward.clone().multiplyScalar(-forwardSpeed * Math.abs(forwardSpeed) * 320.0);
    totalForce.add(forwardDragForce);

    // Vertical drag (damping heave oscillations)
    totalForce.y -= this.linearVelocity.y * 12000.0;

    // Angular damping (pitch, yaw, roll friction against water)
    totalTorque.x -= this.angularVelocity.x * SHIP_CONFIG.dragAngular * 1.2;
    totalTorque.y -= this.angularVelocity.y * SHIP_CONFIG.dragAngular * 1.8;
    totalTorque.z -= this.angularVelocity.z * SHIP_CONFIG.dragAngular * 1.5;

    // Hydrostatic Righting Torque (prevents capsizing and keeps ship upright)
    const euler = new THREE.Euler().setFromQuaternion(this.quaternion, 'YXZ');
    totalTorque.z -= euler.z * SHIP_CONFIG.rightingTorque; // Roll righting
    totalTorque.x -= euler.x * (SHIP_CONFIG.rightingTorque * 0.8); // Pitch righting

    // 5. Integrate Motion (Newton-Euler)
    const acceleration = totalForce.divideScalar(SHIP_CONFIG.mass);
    this.linearVelocity.addScaledVector(acceleration, dt);
    this.position.addScaledVector(this.linearVelocity, dt);

    // Moments of inertia approximation
    const invInertia = new THREE.Vector3(
      1.0 / (SHIP_CONFIG.mass * 24.0), // Pitch inertia
      1.0 / (SHIP_CONFIG.mass * 18.0), // Yaw inertia
      1.0 / (SHIP_CONFIG.mass * 8.0)   // Roll inertia
    );

    this.angularVelocity.x += totalTorque.x * invInertia.x * dt;
    this.angularVelocity.y += totalTorque.y * invInertia.y * dt;
    this.angularVelocity.z += totalTorque.z * invInertia.z * dt;

    // Update quaternion from angular velocity
    const rotDelta = new THREE.Quaternion().setFromAxisAngle(
      this.angularVelocity.clone().normalize(),
      this.angularVelocity.length() * dt
    );
    this.quaternion.multiply(rotDelta).normalize();

    // 6. Apply state to 3D Ship object
    this.ship.position.copy(this.position);
    this.ship.quaternion.copy(this.quaternion);

    // 7. Update Telemetry readings
    const currentEuler = new THREE.Euler().setFromQuaternion(this.quaternion, 'YXZ');
    this.pitchDeg = THREE.MathUtils.radToDeg(currentEuler.x);
    this.rollDeg = THREE.MathUtils.radToDeg(currentEuler.z);
    
    // Heading in nautical degrees (0 to 360)
    let heading = THREE.MathUtils.radToDeg(-currentEuler.y) % 360;
    if (heading < 0) heading += 360;
    this.headingDeg = Math.round(heading);

    // 8. Live Marine Depth Sounder
    if (archipelago) {
      this.currentDepthMeters = archipelago.getWaterDepthAt(this.position);
      this.shallowAlarm = (this.currentDepthMeters < 8.0);
    }
  }
}
