// Multi-point Buoyancy & Hydrodynamics Physics Engine
import * as THREE from 'three';
import { SHIP_CONFIG, GRAVITY } from './constants.js';
import { sampleOcean } from './gerstner.js';

export class ShipPhysics {
  constructor(shipObject) {
    this.ship = shipObject;

    // Physical state
    this.position = new THREE.Vector3(0, 0, 0);
    this.linearVelocity = new THREE.Vector3(0, 0, 0);
    
    this.quaternion = new THREE.Quaternion();
    this.angularVelocity = new THREE.Vector3(0, 0, 0); // pitch, yaw, roll rates

    // Control state
    this.throttle = 0;       // -1.0 to 1.0
    this.rudder = 0;         // -1.0 to 1.0
    this.targetThrottle = 0;
    this.targetRudder = 0;

    // Output telemetry
    this.speedKnots = 0;
    this.headingDeg = 0;
    this.currentWaveHeight = 0;
    this.rollDeg = 0;
    this.pitchDeg = 0;

    // Bow Thruster (-1.0 Port, +1.0 Starboard)
    this.bowThruster = 0;
    this.targetBowThruster = 0;

    // Navigation & Waypoint Autopilot
    this.autopilot = false;
    this.waypoints = [
      { name: 'Channel Marker 1', x: 0, z: 160 },
      { name: 'Cape Horizon Approach', x: 280, z: 420 },
      { name: 'Lighthouse Anchorage', x: 440, z: 580 },
      { name: 'The Needles Passage', x: -380, z: 320 },
      { name: 'Open Ocean Patrol', x: 0, z: 0 }
    ];
    this.activeWaypointIndex = 0;
    this.distToWaypoint = 0;
    this.bearingToWaypoint = 0;
    this.currentDepthMeters = 58.0;
    this.shallowAlarm = false;
  }

  setControls(throttleInput, rudderInput) {
    this.targetThrottle = THREE.MathUtils.clamp(throttleInput, -0.6, 1.0);
    this.targetRudder = THREE.MathUtils.clamp(rudderInput, -1.0, 1.0);
  }

  setBowThruster(val) {
    this.targetBowThruster = THREE.MathUtils.clamp(val, -1.0, 1.0);
  }

  setAutopilot(active) {
    this.autopilot = active;
  }

  update(dt, time, waveScale = 1.0, archipelago = null) {
    // 0. Waypoint Autopilot Navigation
    if (this.autopilot) {
      const wp = this.waypoints[this.activeWaypointIndex];
      const toWp = new THREE.Vector3(wp.x - this.position.x, 0, wp.z - this.position.z);
      this.distToWaypoint = toWp.length();
      const targetHeading = Math.atan2(toWp.x, toWp.z);
      this.bearingToWaypoint = Math.round(((targetHeading * 180) / Math.PI + 360) % 360);

      const currentHeadingRad = (this.headingDeg * Math.PI) / 180;
      let headingError = targetHeading - currentHeadingRad;
      while (headingError > Math.PI) headingError -= Math.PI * 2;
      while (headingError < -Math.PI) headingError += Math.PI * 2;

      this.targetRudder = THREE.MathUtils.clamp(-headingError * 2.2, -1.0, 1.0);
      this.targetThrottle = 0.85;

      if (this.distToWaypoint < 42.0) {
        this.activeWaypointIndex = (this.activeWaypointIndex + 1) % this.waypoints.length;
      }
    }

    // 1. Smooth control inputs (engine throttle lag, hydraulic rudder, electric bow thruster)
    this.throttle = THREE.MathUtils.damp(this.throttle, this.targetThrottle, 2.2, dt);
    this.rudder = THREE.MathUtils.damp(this.rudder, this.targetRudder, 4.5, dt);
    this.bowThruster = THREE.MathUtils.damp(this.bowThruster, this.targetBowThruster, 6.0, dt);

    // Ship local orientation vectors
    const forward = new THREE.Vector3(0, 0, 1).applyQuaternion(this.quaternion).normalize();
    const up = new THREE.Vector3(0, 1, 0).applyQuaternion(this.quaternion).normalize();
    const right = new THREE.Vector3(1, 0, 0).applyQuaternion(this.quaternion).normalize();

    // 2. Accumulate Forces & Torques
    const totalForce = new THREE.Vector3(0, -SHIP_CONFIG.mass * GRAVITY, 0); // Gravity
    const totalTorque = new THREE.Vector3(0, 0, 0);

    // Multi-point probe buoyancy calculation
    let submergedCount = 0;
    let avgWaterHeight = 0;

    for (const probe of SHIP_CONFIG.probes) {
      // World position of the probe on the hull
      const localProbe = new THREE.Vector3(probe.x, probe.y, probe.z);
      const worldProbe = localProbe.clone().applyQuaternion(this.quaternion).add(this.position);

      // Probe velocity
      const r = localProbe.clone().applyQuaternion(this.quaternion);
      const probeVel = this.linearVelocity.clone().add(this.angularVelocity.clone().cross(r));

      // Query wave height & normal at probe position
      const oceanSample = sampleOcean(worldProbe.x, worldProbe.z, time, waveScale);
      const submersion = oceanSample.height - worldProbe.y;
      avgWaterHeight += oceanSample.height;

      if (submersion > 0) {
        submergedCount++;
        // Spring + Damping buoyancy force
        const fUp = (SHIP_CONFIG.buoyancyStiffness * submersion - SHIP_CONFIG.buoyancyDamping * probeVel.y) * probe.weight;
        const clampedFUp = Math.max(0, fUp);

        const forceVec = new THREE.Vector3(0, clampedFUp, 0);
        totalForce.add(forceVec);

        // Torque generated by this hull probe: tau = r x F
        const torque = r.clone().cross(forceVec);
        totalTorque.add(torque);
      }
    }

    avgWaterHeight /= SHIP_CONFIG.probes.length;
    this.currentWaveHeight = Math.abs(avgWaterHeight);

    // 3. Propulsion & Rudder Steering
    const thrustMagnitude = this.throttle >= 0
      ? this.throttle * SHIP_CONFIG.maxEnginePower
      : this.throttle * SHIP_CONFIG.maxReversePower;

    const thrustForce = forward.clone().multiplyScalar(thrustMagnitude);
    totalForce.add(thrustForce);

    // Rudder creates turning torque only when ship is moving through water (around local UP axis)
    const forwardSpeed = this.linearVelocity.dot(forward);
    this.speedKnots = forwardSpeed * 1.94384; // m/s to knots

    const rudderTorqueMagnitude = -this.rudder * SHIP_CONFIG.maxRudderAngle * forwardSpeed * 4500.0;
    totalTorque.addScaledVector(up, rudderTorqueMagnitude);

    // Centrifugal rolling moment (ship heels outward during turns around local FORWARD axis)
    const heelTorque = this.rudder * forwardSpeed * 4200.0;
    totalTorque.addScaledVector(forward, heelTorque);

    // 3b. Electric Bow Thruster Force & Turning Moment (360° spin & crab docking around local UP axis)
    if (Math.abs(this.bowThruster) > 0.01) {
      const thrusterMag = this.bowThruster * 34000.0;
      totalForce.add(right.clone().multiplyScalar(thrusterMag));
      // Moment arm at bow (7.2m forward of center of gravity)
      totalTorque.addScaledVector(up, -thrusterMag * 7.2);
    }

    // 4. Hydrodynamic Resistance (Linear & Angular Drag in World Space)
    // Lateral drag (ships resist sideways sliding heavily)
    const lateralSpeed = this.linearVelocity.dot(right);
    const lateralDragForce = right.clone().multiplyScalar(-lateralSpeed * SHIP_CONFIG.dragLinear * 4.5);
    totalForce.add(lateralDragForce);

    // Forward drag (increases with square of speed)
    const forwardDragForce = forward.clone().multiplyScalar(-forwardSpeed * Math.abs(forwardSpeed) * 320.0);
    totalForce.add(forwardDragForce);

    // Vertical drag (damping heave oscillations)
    totalForce.y -= this.linearVelocity.y * 14000.0;

    // Angular damping against water in world coordinates
    totalTorque.addScaledVector(this.angularVelocity, -SHIP_CONFIG.dragAngular * 3.2);

    // 5. Hydrostatic Righting Moment (Coordinate-free Ballast Keel Stabilization)
    // Computes restoring torque vector that rotates ship's local UP back to world UP
    const worldUp = new THREE.Vector3(0, 1, 0);
    const rightingAxis = new THREE.Vector3().crossVectors(up, worldUp);
    const sinTilt = rightingAxis.length();
    if (sinTilt > 0.0001) {
      rightingAxis.normalize();
      const tiltAngle = Math.asin(Math.min(1.0, sinTilt));
      // Deep keel ballast provides sharp restoring torque preventing capsize
      const stiffness = SHIP_CONFIG.rightingTorque * (1.0 + Math.pow(tiltAngle / 0.35, 2.0) * 3.5);
      totalTorque.addScaledVector(rightingAxis, tiltAngle * stiffness);
    }

    // 6. Integrate Motion (Newton-Euler)
    const acceleration = totalForce.divideScalar(SHIP_CONFIG.mass);
    this.linearVelocity.addScaledVector(acceleration, dt);

    // Island Shore Grounding / Collision (Prevents sailing through islands and cliff tumbling)
    if (archipelago && archipelago.islands) {
      for (const isle of archipelago.islands) {
        const dx = this.position.x - isle.pos.x;
        const dz = this.position.z - isle.pos.z;
        const dist = Math.sqrt(dx * dx + dz * dz);
        const minClearance = isle.radius + 12.0;
        if (dist < minClearance && dist > 0.1) {
          const nx = dx / dist;
          const nz = dz / dist;
          const penetration = minClearance - dist;
          this.position.x += nx * penetration * 0.9;
          this.position.z += nz * penetration * 0.9;

          // Kill velocity heading into shore
          const vDotN = this.linearVelocity.x * nx + this.linearVelocity.z * nz;
          if (vDotN < 0) {
            this.linearVelocity.x -= nx * vDotN * 1.6;
            this.linearVelocity.z -= nz * vDotN * 1.6;
          }
        }
      }
    }

    this.position.addScaledVector(this.linearVelocity, dt);

    // World angular acceleration
    const angularAcceleration = totalTorque.divideScalar(SHIP_CONFIG.mass * 18.0);
    this.angularVelocity.addScaledVector(angularAcceleration, dt);
    this.angularVelocity.multiplyScalar(Math.exp(-2.5 * dt)); // Viscous rotational decay
    this.angularVelocity.clampLength(0, 1.6); // Prevent catastrophic rotational spin

    // Update quaternion in WORLD space
    const angSpeed = this.angularVelocity.length();
    if (angSpeed > 0.0001) {
      const rotDelta = new THREE.Quaternion().setFromAxisAngle(
        this.angularVelocity.clone().normalize(),
        angSpeed * dt
      );
      this.quaternion.premultiply(rotDelta).normalize();
    }

    // 7. Apply state to 3D Ship object
    this.ship.position.copy(this.position);
    this.ship.quaternion.copy(this.quaternion);

    // 8. Robust Attitude & Heading Telemetry (Coordinate-free, No Gimbal Lock)
    // Pitch: bow inclination relative to horizon
    this.pitchDeg = THREE.MathUtils.radToDeg(Math.asin(THREE.MathUtils.clamp(forward.y, -1.0, 1.0)));
    // Roll: starboard rail inclination relative to horizon
    this.rollDeg = THREE.MathUtils.radToDeg(Math.asin(THREE.MathUtils.clamp(right.y, -1.0, 1.0)));
    
    // Heading in nautical degrees (0 to 360, where 0=N, 90=E, 180=S, 270=W)
    let heading = THREE.MathUtils.radToDeg(Math.atan2(forward.x, forward.z));
    if (heading < 0) heading += 360;
    this.headingDeg = Math.round(heading) % 360;

    // 9. Live Marine Depth Sounder
    if (archipelago) {
      this.currentDepthMeters = archipelago.getWaterDepthAt(this.position);
      this.shallowAlarm = (this.currentDepthMeters < 8.0);
    }
  }
}
